"""Add clothes and outfit tables

Revision ID: 227a4056f36d
Revises: 
Create Date: 2025-01-11 20:42:43.580875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '227a4056f36d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clothing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clothing_description'), 'clothing', ['description'], unique=False)
    op.create_index(op.f('ix_clothing_id'), 'clothing', ['id'], unique=False)
    op.create_index(op.f('ix_clothing_name'), 'clothing', ['name'], unique=False)
    op.create_table('outfits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outfits_description'), 'outfits', ['description'], unique=False)
    op.create_index(op.f('ix_outfits_id'), 'outfits', ['id'], unique=False)
    op.create_index(op.f('ix_outfits_name'), 'outfits', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outfits_name'), table_name='outfits')
    op.drop_index(op.f('ix_outfits_id'), table_name='outfits')
    op.drop_index(op.f('ix_outfits_description'), table_name='outfits')
    op.drop_table('outfits')
    op.drop_index(op.f('ix_clothing_name'), table_name='clothing')
    op.drop_index(op.f('ix_clothing_id'), table_name='clothing')
    op.drop_index(op.f('ix_clothing_description'), table_name='clothing')
    op.drop_table('clothing')
    # ### end Alembic commands ###
